POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJleHAiOjE3Mjk2MDY2MzAsInVzZXJJZCI6MX0.o8fc6Dr-GrrCiQaFhH25Yj42GXC2QoNA9OvJ5yQMIa0

{
    "name": "New event",
    "description": "A new event",
    "location": "A new location",
    "dateTime": "2024-02-11T12:35:00Z"
}
